# Generated by Django 4.0.2 on 2022-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(default='')),
                ('photo', models.ImageField(upload_to='workshops_img/')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='about_us',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='home',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
